packages:
  - apps/*
  - packages/*

overrides:
  brace-expansion@2.1.4: 2.1.3

allowBuilds:
  '@prisma/engines': true
  prisma: true
  esbuild: true
  '@scarf/scarf': false
  msw: true

minimumReleaseAgeExclude:
  - prettier@3.9.6
  - react-dom@19.2.8
  - react@19.2.8
